name: Releases
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step    
        run: exit 1
        continue-on-error: true
      
      - name: Passing step
        run: echo "This step will pass"
  
